// ============================================
// NyayaSahayak — Bundled Reference Data
// States/UTs, Districts, Red Flags, i18n strings
// All data is static & bundled for offline use.
// ============================================

export const STATES_UTS = {
  AN: { name: 'Andhra Pradesh', hc: 'AP High Court', landLaw: 'AP Land Revenue Act 2017', portal: 'https://apolcms.ap.gov.in/', districts: ['Anakapalli', 'Anantapur', 'Bapatla', 'Chittoor', 'East Godavari', 'Eluru', 'Guntur', 'Kakinada', 'Konaseema', 'Krishna', 'Kurnool', 'Manyam', 'NTR', 'Nellore', 'Palnadu', 'Prakasam', 'Sri Sathya Sai', 'Srikakulam', 'Tirupati', 'Visakha', 'Vizianagaram', 'West Godavari', 'YSR Kadapa'], langs: ['te', 'en'] },
  AR: { name: 'Arunachal Pradesh', hc: 'Gauhati HC', landLaw: 'AP Land Revenue Code', districts: ['Anjaw', 'Changlang', 'Dibang Valley', 'East Kameng', 'East Siang', 'Kamle', 'Kra Daadi', 'Kurung Kumey', 'Lepa Rada', 'Lohit', 'Longding', 'Lower Dibang Valley', 'Lower Subansiri', 'Namsai', 'Papum Pare', 'Shi Yomi', 'Siang', 'Tawang', 'Tirap', 'Upper Siang', 'Upper Subansiri', 'West Kameng', 'West Siang'], langs: ['en', 'hi'] },
  AS: { name: 'Assam', hc: 'Gauhati HC', landLaw: 'Assam Land Revenue Reg 1886', portal: 'https://ilrms.assam.gov.in/', districts: ['Baksa', 'Barpeta', 'Biswanath', 'Bongaigaon', 'Cachar', 'Charaideo', 'Chirang', 'Darrang', 'Dhemaji', 'Dhubri', 'Dibrugarh', 'Dima Hasao', 'Goalpara', 'Golaghat', 'Hailakandi', 'Hojai', 'Jorhat', 'Kamrup', 'Kamrup Metro', 'Karbi Anglong', 'Karimganj', 'Kokrajhar', 'Lakhimpur', 'Majuli', 'Morigaon', 'Nagaon', 'Nalbari', 'Sivasagar', 'Sonitpur', 'South Salmara', 'Tinsukia', 'Udalguri', 'West Karbi Anglong'], langs: ['as', 'en'] },
  BR: { name: 'Bihar', hc: 'Patna HC', landLaw: 'Bihar Tenancy Act 1885', portal: 'https://lrc.bih.nic.in/', districts: ['Araria', 'Arwal', 'Aurangabad', 'Banka', 'Begusarai', 'Bhagalpur', 'Bhojpur', 'Buxar', 'Darbhanga', 'East Champaran', 'Gaya', 'Gopalganj', 'Jamui', 'Jehanabad', 'Kaimur', 'Katihar', 'Khagaria', 'Kishanganj', 'Lakhisarai', 'Madhepura', 'Madhubani', 'Munger', 'Muzaffarpur', 'Nalanda', 'Nawada', 'Patna', 'Purnia', 'Rohtas', 'Saharsa', 'Samastipur', 'Saran', 'Sheikhpura', 'Sheohar', 'Sitamarhi', 'Siwan', 'Supaul', 'Vaishali', 'West Champaran'], langs: ['hi', 'en'] },
  CG: { name: 'Chhattisgarh', hc: 'CG HC', landLaw: 'CG Land Revenue Code 1959', portal: 'https://bhuiyan.cg.nic.in/', districts: ['Balod', 'Baloda Bazar', 'Balrampur', 'Bastar', 'Bemetara', 'Bijapur', 'Bilaspur', 'Dantewada', 'Dhamtari', 'Durg', 'Gariaband', 'Gaurela-Pendra-Marwahi', 'Janjgir-Champa', 'Jashpur', 'Kabirdham', 'Kanker', 'Kondagaon', 'Korba', 'Koriya', 'Mahasamund', 'Mungeli', 'Narayanpur', 'Raigarh', 'Raipur', 'Rajnandgaon', 'Sukma', 'Surajpur', 'Surguja'], langs: ['hi', 'en'] },
  GA: { name: 'Goa', hc: 'Bombay HC', landLaw: 'Goa Land Revenue Code 1968', districts: ['North Goa', 'South Goa'], langs: ['en', 'hi', 'mr', 'kn'] },
  GJ: { name: 'Gujarat', hc: 'Gujarat HC', landLaw: 'Bombay LRC Gujarat', portal: 'https://anyror.gujarat.gov.in/', districts: ['Ahmedabad', 'Amreli', 'Anand', 'Aravalli', 'Banaskantha', 'Bharuch', 'Bhavnagar', 'Botad', 'Chhota Udaipur', 'Dahod', 'Dang', 'Devbhoomi Dwarka', 'Gandhinagar', 'Gir Somnath', 'Jamnagar', 'Junagadh', 'Kheda', 'Kutch', 'Mahisagar', 'Mehsana', 'Morbi', 'Narmada', 'Navsari', 'Panchmahal', 'Patan', 'Porbandar', 'Rajkot', 'Sabarkantha', 'Surat', 'Surendranagar', 'Tapi', 'Vadodara', 'Valsad'], langs: ['gu', 'en', 'hi'] },
  HR: { name: 'Haryana', hc: 'Punjab & Haryana HC', landLaw: 'Punjab LRA Haryana', portal: 'https://jamabandi.nic.in/', districts: ['Ambala', 'Bhiwani', 'Charkhi Dadri', 'Faridabad', 'Fatehabad', 'Gurugram', 'Hisar', 'Jhajjar', 'Jind', 'Kaithal', 'Karnal', 'Kurukshetra', 'Mahendragarh', 'Nuh', 'Palwal', 'Panchkula', 'Panipat', 'Rewari', 'Rohtak', 'Sirsa', 'Sonipat', 'Yamunanagar'], langs: ['hi', 'en', 'pa'] },
  HP: { name: 'Himachal Pradesh', hc: 'HP HC', landLaw: 'HP Land Revenue Act', portal: 'https://landrecords.hp.gov.in/', districts: ['Bilaspur', 'Chamba', 'Hamirpur', 'Kangra', 'Kinnaur', 'Kullu', 'Lahaul & Spiti', 'Mandi', 'Shimla', 'Sirmaur', 'Solan', 'Una'], langs: ['hi', 'en'] },
  JK: { name: 'Jammu & Kashmir', hc: 'J&K HC', landLaw: 'J&K Land Revenue Act 1996', portal: 'https://jklandrecords.jk.gov.in/', districts: ['Anantnag', 'Bandipora', 'Baramulla', 'Budgam', 'Doda', 'Ganderbal', 'Jammu', 'Kathua', 'Kishtwar', 'Kulgam', 'Kupwara', 'Poonch', 'Pulwama', 'Rajouri', 'Ramban', 'Reasi', 'Samba', 'Shopian', 'Srinagar', 'Udhampur'], langs: ['ur', 'en', 'hi'] },
  JH: { name: 'Jharkhand', hc: 'Jharkhand HC', landLaw: 'Jharkhand LRA 1957', portal: 'https://jharbhoomi.jharkhand.gov.in/', districts: ['Bokaro', 'Chatra', 'Deoghar', 'Dhanbad', 'Dumka', 'East Singhbhum', 'Garhwa', 'Giridih', 'Godda', 'Gumla', 'Hazaribagh', 'Jamtara', 'Khunti', 'Koderma', 'Latehar', 'Lohardaga', 'Pakur', 'Palamu', 'Ramgarh', 'Ranchi', 'Sahibganj', 'Saraikela', 'Simdega', 'West Singhbhum'], langs: ['hi', 'en'] },
  KA: { name: 'Karnataka', hc: 'Karnataka HC', landLaw: 'Karnataka LRA 1964', portal: 'https://landrecords.karnataka.gov.in/', districts: ['Bagalkot', 'Ballari', 'Belagavi', 'Bengaluru Rural', 'Bengaluru Urban', 'Bidar', 'Chamarajanagar', 'Chikballapur', 'Chikkamagaluru', 'Chitradurga', 'Dakshina Kannada', 'Davanagere', 'Dharwad', 'Gadag', 'Hassan', 'Haveri', 'Kalaburagi', 'Kodagu', 'Kolar', 'Koppal', 'Mandya', 'Mysuru', 'Raichur', 'Ramanagara', 'Shivamogga', 'Tumakuru', 'Udupi', 'Uttara Kannada', 'Vijayanagara', 'Vijayapura', 'Yadgir'], langs: ['kn', 'en'] },
  KL: { name: 'Kerala', hc: 'Kerala HC', landLaw: 'Kerala Land Reforms Act 1963', portal: 'https://keralarecords.kerala.gov.in/', districts: ['Alappuzha', 'Ernakulam', 'Idukki', 'Kannur', 'Kasaragod', 'Kollam', 'Kottayam', 'Malappuram', 'Palakkad', 'Pathanamthitta', 'Thiruvananthapuram', 'Thrissur', 'Wayanad'], langs: ['ml', 'en'] },
  MP: { name: 'Madhya Pradesh', hc: 'MP HC', landLaw: 'MP Land Revenue Code 1959', portal: 'https://mpedistrict.gov.in/', districts: ['Agar Malwa', 'Alirajpur', 'Anuppur', 'Ashoknagar', 'Balaghat', 'Barwani', 'Betul', 'Bhind', 'Bhopal', 'Burhanpur', 'Chhatarpur', 'Chhindwara', 'Damoh', 'Datia', 'Dewas', 'Dhar', 'Dindori', 'Guna', 'Gwalior', 'Harda', 'Hoshangabad', 'Indore', 'Jabalpur', 'Jhabua', 'Katni', 'Khandwa', 'Khargone', 'Mandla', 'Mandsaur', 'Morena', 'Narsinghpur', 'Neemuch', 'Niwari', 'Panna', 'Raisen', 'Rajgarh', 'Ratlam', 'Rewa', 'Sagar', 'Satna', 'Sehore', 'Seoni', 'Shahdol', 'Shajapur', 'Sheopur', 'Shivpuri', 'Sidhi', 'Singrauli', 'Tikamgarh', 'Ujjain', 'Umaria', 'Vidisha'], langs: ['hi', 'en'] },
  MH: { name: 'Maharashtra', hc: 'Bombay HC', landLaw: 'Maharashtra LRC 1966', portal: 'https://bhulekh.mahabhumi.gov.in/', districts: ['Ahmednagar', 'Akola', 'Amravati', 'Aurangabad', 'Beed', 'Bhandara', 'Buldhana', 'Chandrapur', 'Dhule', 'Gadchiroli', 'Gondia', 'Hingoli', 'Jalgaon', 'Jalna', 'Kolhapur', 'Latur', 'Mumbai City', 'Mumbai Suburban', 'Nagpur', 'Nanded', 'Nandurbar', 'Nashik', 'Osmanabad', 'Palghar', 'Parbhani', 'Pune', 'Raigad', 'Ratnagiri', 'Sangli', 'Satara', 'Sindhudurg', 'Solapur', 'Thane', 'Wardha', 'Washim', 'Yavatmal'], langs: ['mr', 'en', 'hi'] },
  MN: { name: 'Manipur', hc: 'Manipur HC', landLaw: 'Manipur LRA', districts: ['Bishnupur', 'Chandel', 'Churachandpur', 'Imphal East', 'Imphal West', 'Jiribam', 'Kakching', 'Kamjong', 'Kangpokpi', 'Noney', 'Pherzawl', 'Senapati', 'Tamenglong', 'Tengnoupal', 'Thoubal', 'Ukhrul'], langs: ['en', 'hi'] },
  ML: { name: 'Meghalaya', hc: 'Meghalaya HC', landLaw: 'Meghalaya LRA', districts: ['East Garo Hills', 'East Jaintia Hills', 'East Khasi Hills', 'North Garo Hills', 'Ri Bhoi', 'South Garo Hills', 'West Garo Hills', 'West Jaintia Hills', 'West Khasi Hills', 'South West Garo Hills', 'South West Khasi Hills'], langs: ['en'] },
  MZ: { name: 'Mizoram', hc: 'Gauhati HC', landLaw: 'Mizoram LRA', districts: ['Aizawl', 'Champhai', 'Hnahthial', 'Khawzawl', 'Kolasib', 'Lawngtlai', 'Lunglei', 'Mamit', 'Saiha', 'Saitual', 'Serchhip'], langs: ['en'] },
  NL: { name: 'Nagaland', hc: 'Gauhati HC', landLaw: 'Nagaland LRA', districts: ['Chumukedima', 'Dimapur', 'Kiphire', 'Kohima', 'Longleng', 'Mokokchung', 'Mon', 'Niuland', 'Noklak', 'Peren', 'Phek', 'Shamator', 'Tseminyu', 'Tuensang', 'Wokha', 'Zunheboto'], langs: ['en'] },
  OD: { name: 'Odisha', hc: 'Orissa HC', landLaw: 'Odisha LRA 1956', portal: 'https://bhulekh.ori.nic.in/', districts: ['Angul', 'Balangir', 'Balasore', 'Bargarh', 'Bhadrak', 'Boudh', 'Cuttack', 'Deogarh', 'Dhenkanal', 'Gajapati', 'Ganjam', 'Jagatsinghpur', 'Jajpur', 'Jharsuguda', 'Kalahandi', 'Kandhamal', 'Kendrapara', 'Kendujhar', 'Khordha', 'Koraput', 'Malkangiri', 'Mayurbhanj', 'Nabarangpur', 'Nayagarh', 'Nuapada', 'Puri', 'Rayagada', 'Sambalpur', 'Subarnapur', 'Sundargarh'], langs: ['or', 'en', 'hi'] },
  PB: { name: 'Punjab', hc: 'Punjab & Haryana HC', landLaw: 'Punjab LRA 1887', portal: 'https://jamabandi.punjab.gov.in/', districts: ['Amritsar', 'Barnala', 'Bathinda', 'Faridkot', 'Fatehgarh Sahib', 'Fazilka', 'Ferozepur', 'Gurdaspur', 'Hoshiarpur', 'Jalandhar', 'Kapurthala', 'Ludhiana', 'Malerkotla', 'Mansa', 'Moga', 'Pathankot', 'Patiala', 'Rupnagar', 'SAS Nagar', 'Sangrur', 'SBS Nagar', 'Sri Muktsar Sahib', 'Tarn Taran'], langs: ['pa', 'en', 'hi'] },
  RJ: { name: 'Rajasthan', hc: 'Rajasthan HC', landLaw: 'Rajasthan LRA 1956', portal: 'https://apnakhata.raj.nic.in/', districts: ['Ajmer', 'Alwar', 'Banswara', 'Baran', 'Barmer', 'Bharatpur', 'Bhilwara', 'Bikaner', 'Bundi', 'Chittorgarh', 'Churu', 'Dausa', 'Dholpur', 'Dungarpur', 'Hanumangarh', 'Jaipur', 'Jaisalmer', 'Jalore', 'Jhalawar', 'Jhunjhunu', 'Jodhpur', 'Karauli', 'Kota', 'Nagaur', 'Pali', 'Pratapgarh', 'Rajsamand', 'Sawai Madhopur', 'Sikar', 'Sirohi', 'Sri Ganganagar', 'Tonk', 'Udaipur'], langs: ['hi', 'en'] },
  SK: { name: 'Sikkim', hc: 'Sikkim HC', landLaw: 'Sikkim LRA', districts: ['East Sikkim', 'North Sikkim', 'South Sikkim', 'West Sikkim', 'Pakyong', 'Soreng'], langs: ['en'] },
  TN: { name: 'Tamil Nadu', hc: 'Madras HC', landLaw: 'TN Land Revenue Act 1864', portal: 'https://eservices.tn.gov.in/', districts: ['Ariyalur', 'Chengalpattu', 'Chennai', 'Coimbatore', 'Cuddalore', 'Dharmapuri', 'Dindigul', 'Erode', 'Kallakurichi', 'Kanchipuram', 'Kanyakumari', 'Karur', 'Krishnagiri', 'Madurai', 'Mayiladuthurai', 'Nagapattinam', 'Namakkal', 'Nilgiris', 'Perambalur', 'Pudukkottai', 'Ramanathapuram', 'Ranipet', 'Salem', 'Sivagangai', 'Tenkasi', 'Thanjavur', 'Theni', 'Thoothukudi', 'Tiruchirappalli', 'Tirunelveli', 'Tirupathur', 'Tiruppur', 'Tiruvallur', 'Tiruvannamalai', 'Tiruvarur', 'Vellore', 'Viluppuram', 'Virudhunagar'], langs: ['ta', 'en'] },
  TS: { name: 'Telangana', hc: 'Telangana HC', landLaw: 'Telangana LRA 2017', portal: 'https://dharani.telangana.gov.in/', districts: ['Adilabad', 'Bhadradri Kothagudem', 'Hyderabad', 'Jagtial', 'Jangaon', 'Jayashankar', 'Jogulamba', 'Kamareddy', 'Karimnagar', 'Khammam', 'Kumuram Bheem', 'Mahabubabad', 'Mahabubnagar', 'Mancherial', 'Medak', 'Medchal', 'Mulugu', 'Nalgonda', 'Narayanpet', 'Nirmal', 'Nizamabad', 'Peddapalli', 'Rajanna Sircilla', 'Rangareddy', 'Sangareddy', 'Siddipet', 'Suryapet', 'Vikarabad', 'Wanaparthy', 'Warangal', 'Yadadri'], langs: ['te', 'en', 'ur'] },
  TR: { name: 'Tripura', hc: 'Tripura HC', landLaw: 'Tripura LRA', districts: ['Dhalai', 'Gomati', 'Khowai', 'North Tripura', 'Sepahijala', 'South Tripura', 'Unakoti', 'West Tripura'], langs: ['bn', 'en'] },
  UP: { name: 'Uttar Pradesh', hc: 'Allahabad HC', landLaw: 'UP LRA 1901', portal: 'https://bhulekh.up.nic.in/', districts: ['Agra', 'Aligarh', 'Allahabad', 'Ambedkar Nagar', 'Amethi', 'Amroha', 'Auraiya', 'Ayodhya', 'Azamgarh', 'Baghpat', 'Bahraich', 'Ballia', 'Balrampur', 'Banda', 'Barabanki', 'Bareilly', 'Basti', 'Bhadohi', 'Bijnor', 'Budaun', 'Bulandshahr', 'Chandauli', 'Chitrakoot', 'Deoria', 'Etah', 'Etawah', 'Farrukhabad', 'Fatehpur', 'Firozabad', 'Gautam Buddha Nagar', 'Ghaziabad', 'Ghazipur', 'Gonda', 'Gorakhpur', 'Hamirpur', 'Hapur', 'Hardoi', 'Hathras', 'Jalaun', 'Jaunpur', 'Jhansi', 'Kannauj', 'Kanpur Dehat', 'Kanpur Nagar', 'Kasganj', 'Kaushambi', 'Kheri', 'Kushinagar', 'Lalitpur', 'Lucknow', 'Maharajganj', 'Mahoba', 'Mainpuri', 'Mathura', 'Mau', 'Meerut', 'Mirzapur', 'Moradabad', 'Muzaffarnagar', 'Pilibhit', 'Pratapgarh', 'Raebareli', 'Rampur', 'Saharanpur', 'Sambhal', 'Sant Kabir Nagar', 'Shahjahanpur', 'Shamli', 'Shrawasti', 'Siddharthnagar', 'Sitapur', 'Sonbhadra', 'Sultanpur', 'Unnao', 'Varanasi'], langs: ['hi', 'en', 'ur'] },
  UK: { name: 'Uttarakhand', hc: 'Uttarakhand HC', landLaw: 'Uttarakhand LRA', portal: 'https://bhulekh.uk.gov.in/', districts: ['Almora', 'Bageshwar', 'Chamoli', 'Champawat', 'Dehradun', 'Haridwar', 'Nainital', 'Pauri Garhwal', 'Pithoragarh', 'Rudraprayag', 'Tehri Garhwal', 'Udham Singh Nagar', 'Uttarkashi'], langs: ['hi', 'en'] },
  WB: { name: 'West Bengal', hc: 'Calcutta HC', landLaw: 'WB Land Reforms Act 1955', portal: 'https://banglarbhumi.gov.in/', districts: ['Alipurduar', 'Bankura', 'Birbhum', 'Cooch Behar', 'Dakshin Dinajpur', 'Darjeeling', 'Hooghly', 'Howrah', 'Jalpaiguri', 'Jhargram', 'Kalimpong', 'Kolkata', 'Malda', 'Murshidabad', 'Nadia', 'North 24 Parganas', 'Paschim Bardhaman', 'Paschim Medinipur', 'Purba Bardhaman', 'Purba Medinipur', 'Purulia', 'South 24 Parganas', 'Uttar Dinajpur'], langs: ['bn', 'en', 'hi'] },
  CH: { name: 'Chandigarh', hc: 'Punjab & Haryana HC', landLaw: 'Punjab LRA', districts: ['Chandigarh'], langs: ['en', 'hi', 'pa'] },
  DN: { name: 'Dadra & Nagar Haveli and Daman & Diu', hc: 'Bombay HC', landLaw: 'Bombay LRC', districts: ['Dadra & Nagar Haveli', 'Daman', 'Diu'], langs: ['gu', 'hi', 'en'] },
  DL: { name: 'Delhi', hc: 'Delhi HC', landLaw: 'Delhi LRA', portal: 'https://dlrc.delhigovt.nic.in/', districts: ['Central Delhi', 'East Delhi', 'New Delhi', 'North Delhi', 'North East Delhi', 'North West Delhi', 'Shahdara', 'South Delhi', 'South East Delhi', 'South West Delhi', 'West Delhi'], langs: ['hi', 'en', 'ur', 'pa'] },
  PY: { name: 'Puducherry', hc: 'Madras HC', landLaw: 'Pondicherry LRA', districts: ['Karaikal', 'Mahe', 'Puducherry', 'Yanam'], langs: ['ta', 'en', 'te'] }
};

export const RED_FLAGS_DB = [
  { id: 1, flag: 'noEnrollment', title: { en: 'No Bar Council Enrollment Number', hi: 'बार काउंसिल पंजीकरण संख्या नहीं' }, desc: { en: 'Every lawyer must have a Bar Council ID. If your attorney refuses to share it, that\'s a major red flag.', hi: 'हर वकील का बार काउंसिल ID होना चाहिए। यदि आपका वकील देने से मना करे तो यह बड़ा रेड फ्लैग है।' }, action: { en: 'Verify on barcouncilofindia.org', hi: 'barcouncilofindia.org पर सत्यापित करें' }, severity: 'critical' },
  { id: 2, flag: 'excessiveFee', title: { en: 'Unreasonably High Fee', hi: 'अत्यधिक फीस' }, desc: { en: 'Fee for simple cases should be ₹5,000-25,000. If they ask for lakhs upfront, be suspicious.', hi: 'सरल मामलों के लिए फीस ₹5,000-25,000 होनी चाहिए। यदि वे लाखों मांगें तो संदेह करें।' }, action: { en: 'Get quotes from 3+ attorneys', hi: '3+ वकीलों से कोटेशन लें' }, severity: 'high' },
  { id: 3, flag: 'fullPaymentNoWork', title: { en: 'Full Fee Paid But No Work', hi: 'पूरी फीस ली लेकिन काम नहीं' }, desc: { en: 'If you paid full amount but attorney has done nothing in 30 days, this is serious malpractice.', hi: 'यदि आपने पूरा भुगतान किया लेकिन वकील ने 30 दिनों में कुछ नहीं किया तो यह गंभीर कदाचार है।' }, action: { en: 'Send legal notice, then Bar Council complaint', hi: 'कानूनी नोटिस भेजें, फिर बार काउंसिल शिकायत' }, severity: 'critical' },
  { id: 4, flag: 'noWrittenAgreement', title: { en: 'No Written Fee Agreement', hi: 'लिखित फीस समझौता नहीं' }, desc: { en: 'Always insist on written agreement mentioning scope of work, fees, timeline.', hi: 'हमेशा कार्यक्षेत्र, फीस, समयसीमा का उल्लेख करते हुए लिखित समझौते पर जोर दें।' }, action: { en: 'Draft agreement now, get it signed', hi: 'अभी समझौता बनाएं, हस्ताक्षर कराएं' }, severity: 'high' },
  { id: 5, flag: 'noCaseDiscussion', title: { en: 'Never Discusses Case Strategy', hi: 'कभी केस रणनीति पर चर्चा नहीं' }, desc: { en: 'Attorney should explain strategy, options, pros/cons.', hi: 'वकील को रणनीति, विकल्प, फायदे/नुकसान समझाना चाहिए।' }, action: { en: 'Demand strategy meeting', hi: 'रणनीति बैठक की मांग करें' }, severity: 'medium' },
  { id: 6, flag: 'falseGuarantee', title: { en: 'Guaranteed Win Promise', hi: 'जीत की गारंटी' }, desc: { en: 'No attorney can guarantee case outcome. Promising 100% win is a red flag.', hi: 'कोई वकील मामले का परिणाम गारंटी नहीं दे सकता। 100% जीत का वादा रेड फ्लैग है।' }, action: { en: 'Run away! This is fraud', hi: 'भागो! यह धोखाधड़ी है' }, severity: 'critical' },
  { id: 7, flag: 'noCaseFile', title: { en: 'Won\'t Share Case File', hi: 'केस फाइल साझा नहीं' }, desc: { en: 'You have right to your case file. Refusal means hiding something.', hi: 'आपको अपनी केस फाइल का अधिकार है। मना करने का मतलब कुछ छिपाना है।' }, action: { en: 'Demand copy of entire case file', hi: 'पूरी केस फाइल की प्रति मांगें' }, severity: 'high' },
  { id: 8, flag: 'unreachable', title: { en: 'Always Unreachable', hi: 'हमेशा अनुपलब्ध' }, desc: { en: 'Attorney should respond within 24-48 hours. If always unreachable, change.', hi: 'वकील को 24-48 घंटों में जवाब देना चाहिए। हमेशा अनुपलब्ध हो तो बदलें।' }, action: { en: 'Document non-responses, consider change', hi: 'गैर-प्रतिक्रिया दस्तावेज, बदलने पर विचार' }, severity: 'medium' },
  { id: 9, flag: 'clientCollusion', title: { en: 'Suspected Collusion with Opposite Party', hi: 'विपक्षी पक्ष से संदिग्ध मिलीभगत' }, desc: { en: 'Signs: opposing party knows your strategy, sudden settlements favorable to them, etc.', hi: 'संकेत: विरोधी पक्ष को आपकी रणनीति पता है, अचानक समझौता उनके पक्ष में।' }, action: { en: 'File police complaint + Bar Council', hi: 'पुलिस शिकायत + बार काउंसिल' }, severity: 'critical' },
  { id: 10, flag: 'noVakalatnama', title: { en: 'No Vakalatnama Filed', hi: 'वकालतनामा दाखिल नहीं' }, desc: { en: 'Vakalatnama is mandatory for attorney to represent you. No Vakalatnama = unauthorized practice.', hi: 'वकील के लिए वकालतनामा अनिवार्य है। नहीं = अनधिकृत अभ्यास।' }, action: { en: 'Check if Vakalatnama is on record', hi: 'जाँचें कि वकालतनामा रिकॉर्ड पर है' }, severity: 'high' },
  { id: 11, flag: 'clientNotAttending', title: { en: 'Attorney Doesn\'t Want You in Court', hi: 'वकील नहीं चाहता कि आप अदालत में आएं' }, desc: { en: 'You have right to attend. If attorney discourages, ask why.', hi: 'आपको उपस्थित होने का अधिकार है। वकील हतोत्साहित करे तो कारण पूछें।' }, action: { en: 'Attend all hearings yourself', hi: 'सभी सुनवाई में स्वयं जाएं' }, severity: 'medium' },
  { id: 12, flag: 'extraCourtVisit', title: { en: 'Asking for Extra Money for Court Visits', hi: 'अदालत दौरे के लिए अतिरिक्त पैसे' }, desc: { en: 'Court visits are part of attorney\'s job. Should be included in fee.', hi: 'अदालत दौरा वकील के काम का हिस्सा है। फीस में शामिल होना चाहिए।' }, action: { en: 'Refuse, refer to fee agreement', hi: 'मना करें, फीस समझौते देखें' }, severity: 'high' },
  { id: 13, flag: 'takesBribe', title: { en: 'Asks for Bribe for Court Staff', hi: 'कोर्ट कर्मचारियों के लिए रिश्वत' }, desc: { en: 'Never pay bribes. Court fees are official. Everything else is illegal.', hi: 'कभी रिश्वत न दें। कोर्ट फीस आधिकारिक है। बाकी सब अवैध।' }, action: { en: 'Refuse, report to court', hi: 'मना करें, कोर्ट को रिपोर्ट करें' }, severity: 'critical' },
  { id: 14, flag: 'noReceipts', title: { en: 'No Receipts for Payments', hi: 'भुगतान की रसीद नहीं' }, desc: { en: 'Always get written receipt with date, amount, purpose for every payment.', hi: 'हर भुगतान के लिए तारीख, राशि, उद्देश्य के साथ लिखित रसीद लें।' }, action: { en: 'Demand receipts from now', hi: 'अब से रसीद मांगें' }, severity: 'high' },
  { id: 15, flag: 'advantageTaken', title: { en: 'Asks You to Sign Blank Papers', hi: 'खाली कागज पर हस्ताक्षर' }, desc: { en: 'NEVER sign blank papers. This is classic fraud technique.', hi: 'कभी खाली कागज पर हस्ताक्षर न करें। यह क्लासिक धोखाधड़ी है।' }, action: { en: 'Refuse absolutely', hi: 'बिल्कुल मना करें' }, severity: 'critical' }
];

export const I18N = {
  home: { en: 'Home', hi: 'होम', te: 'హోమ్', ta: 'முகப்பு', kn: 'ಮುಖಪುಟ', bn: 'হোম', mr: 'मुख्यपृष्ठ', gu: 'હોમ', pa: 'ਹੋਮ', ml: 'ഹോം', or: 'ହୋମ', ur: 'ہوم' },
  mycase: { en: 'My Case', hi: 'मेरा मामला', te: 'నా కేసు', ta: 'என் வழக்கு', kn: 'ನನ್ನ ಪ್ರಕರಣ', bn: 'আমার মামলা', mr: 'माझा केस', gu: 'મારો કેસ', pa: 'ਮੇਰਾ ਕੇਸ', ml: 'എന്റെ കേസ്', or: 'ମୋ କେସ', ur: 'میرا کیس' },
  guide: { en: 'Step Guide', hi: 'मार्गदर्शन', te: 'మార్గదర్శకత్వం', ta: 'வழிகாட்டுதல்', kn: 'ಮಾರ್ಗದರ್ಶನ', bn: 'নির্দেশনা', mr: 'मार्गदर्शन', gu: 'માર્ગદર્શન', pa: 'ਮਾਰਗਦਰਸ਼ਨ', ml: 'വഴികാട്ടൽ', or: 'ମାର୍ଗଦର୍ଶନ', ur: 'رہنمائی' },
  redflags: { en: 'Red Flags', hi: 'रेड फ्लैग', te: 'రెడ్ ఫ్లాగ్స్', ta: 'சிவப்பு கொடிகள்', kn: 'ರೆಡ್ ಫ್ಲ್ಯಾಗ್‌ಗಳು', bn: 'লাল পতাকা', mr: 'रेड फ्लॅग', gu: 'રેડ ફ્લેગ', pa: 'ਰੈੱਡ ਫਲੈਗ', ml: 'ചുവന്ന പതാകകൾ', or: 'ରେଡ ଫ୍ଲାଗ', ur: 'ریڈ فلیگز' },
  attorney: { en: 'Attorney', hi: 'वकील', te: 'న్యాయవాది', ta: 'வழக்கறிஞர்', kn: 'ವಕೀಲ', bn: 'আইনজীবী', mr: 'वकील', gu: 'વકીલ', pa: 'ਵਕੀਲ', ml: 'അഭിഭാഷകൻ', or: 'ଓକିଲ', ur: 'وکیل' },
  analyzer: { en: 'AI Analyzer', hi: 'AI विश्लेषक', te: 'AI విశ్లేషకుడు', ta: 'AI பகுப்பாய்வி', kn: 'AI ವಿಶ್ಲೇಷಕ', bn: 'AI বিশ্লেষক', mr: 'AI विश्लेषक', gu: 'AI વિશ્લેષક', pa: 'AI ਵਿਸ਼ਲੇਸ਼ਕ', ml: 'AI വിശകലനം', or: 'AI ବିଶ୍ଲେଷକ', ur: 'AI تجزیہ کار' },
  drafts: { en: 'Drafts', hi: 'मसौदे', te: 'డ్రాఫ్ట్‌లు', ta: 'வரைவுகள்', kn: 'ಕರಡುಗಳು', bn: 'খসড়া', mr: 'मसुदे', gu: 'ડ્રાફ્ટ', pa: 'ਡਰਾਫਟ', ml: 'ഡ്രാഫ്റ്റുകൾ', or: 'ଡ୍ରାଫ୍ଟ', ur: 'مسودے' },
  cases: { en: 'Case Status', hi: 'केस स्थिति', te: 'కేసు స్థితి', ta: 'வழக்கு நிலை', kn: 'ಪ್ರಕರಣ ಸ್ಥಿತಿ', bn: 'মামলার অবস্থা', mr: 'केस स्थिती', gu: 'કેસ સ્થિતિ', pa: 'ਕੇਸ ਸਥਿਤੀ', ml: 'കേസ് നില', or: 'କେସ ସ୍ଥିତି', ur: 'کیس اسٹیٹس' },
  nearby: { en: 'Nearby', hi: 'पास के', te: 'సమీపంలో', ta: 'அருகில்', kn: 'ಹತ್ತಿರ', bn: 'কাছাকাছি', mr: 'जवळ', gu: 'નજીક', pa: 'ਨੇੜੇ', ml: 'സമീപം', or: 'ନିକଟରେ', ur: 'قریب' },
  rights: { en: 'Rights', hi: 'अधिकार', te: 'హక్కులు', ta: 'உரிமைகள்', kn: 'ಹಕ್ಕುಗಳು', bn: 'অধিকার', mr: 'हक्क', gu: 'અધિકાર', pa: 'ਅਧਿਕਾਰ', ml: 'അവകാശങ്ങൾ', or: 'ଅଧିକାର', ur: 'حقوق' },
  helpline: { en: 'Helpline', hi: 'सहायता', te: 'సహాయం', ta: 'உதவி', kn: 'ಸಹಾಯ', bn: 'সাহায্য', mr: 'मदत', gu: 'સહાય', pa: 'ਮਦਦ', ml: 'സഹായം', or: 'ସହାୟତା', ur: 'مدد' }
};
